source "https://rubygems.org"

git_source(:github) {|cli-data-gem-assessment-v-000| "https://github.com/thekevinhuang/cli-data-gem-assessment-v-000" }

# Specify your gem's dependencies in amaz_scrape.gemspec
gemspec
gem 'nokogiri'
gem 'pry'
gem 'openuri'